{% set name = "biolmai" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/biolmai-{{ version }}.tar.gz
  sha256: c6ecb73871cffb64336bc47f140a1f3c114f43ce7a1dc702a41025aaf001da64

build:
  entry_points:
    - biolmai=biolmai.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - click >=6.0
    - requests
    - pandas
    - aiohttp
    - aiodns
    - httpx >=0.23.0
    - httpcore
    - synchronicity >=0.5.0
    - async-lru
    - aiofiles
    - aiohttp <=3.8.6  # [py<312]
    - aiohttp >=3.9.0  # [py>=312]

test:
  imports:
    - biolmai
  commands:
    - pip check
    - biolmai --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BioLM/py-biolm
  summary: Python client and SDK for https://biolm.ai
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsh87
