{% set name = "biolmai" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/biolmai-{{ version }}.tar.gz
  sha256: c6ecb73871cffb64336bc47f140a1f3c114f43ce7a1dc702a41025aaf001da64

build:
  entry_points:
    - biolmai=biolmai.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=6.0
    - requests
    - pandas
    - aiohttp
    - aiodns

test:
  imports:
    - biolmai
  commands:
    - pip check
    - biolmai --help
  requires:
    - pip

about:
  home: https://github.com/BioLM/py-biolm
  summary: Python client and SDK for https://biolm.ai
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsh87
