{% set name = "biolmai" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/biolmai-{{ version }}.tar.gz
  sha256: cf0de20c00e8e007b6d5d98737f1d9b7797f1f546654f68bc5d2f1efa746377e

build:
  entry_points:
    - biolmai=biolmai.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click >=6.0
    - requests
    - pandas
    - aiodns
    - httpx >=0.23.0
    - httpcore
    - synchronicity >=0.5.0
    - async-lru
    - aiofiles
    - aiohttp <=3.8.6  # [python_version<3.12]
    - aiohttp >=3.9.0  # [python_version>=3.12]

test:
  imports:
    - biolmai
  commands:
    - pip check
    - biolmai --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BioLM/py-biolm
  summary: Python client and SDK for https://biolm.ai
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nsh87
